version: '2'

services:
  nextcloud_2:
    image: gilir/rpi-nextcloud
    container_name: nextcloud
    restart: always
    environment:
      - UID=902
      - GID=902
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - CRON_PERIOD=15m
      - TZ=Europe/Paris
    volumes:
      - nextcloud_2_data:/data
      - nextcloud_2_config:/config
      - nextcloud_2_apps:/apps2
    ports:
      - "9988:9988"
    networks:
      - proxy-network
    labels:
      - "traefik.frontend.rule=Host:nextcloud.lavergne.online"

networks:
  proxy-network:
    external:
      name: proxy-network

volumes:
  nextcloud_2_data:
    external: true
  nextcloud_2_apps:
    external: true
  nextcloud_2_config:
    external: true
