version: '2'

services:
  nextcloud:
    image: gilir/rpi-nextcloud
    container_name: nextcloud
    restart: always
    environment:
      - UID=991
      - GID=991
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - CRON_PERIOD=15m
      - TZ=Europe/Berlin
    external_links:
      - mysql-main
    volumes:
      - nextcloud_data:/data
      - nextcloud_config:/config
      - nextcloud_apps:/apps2
    ports:
      - "9988:9988"
    networks:
      - proxy-network
    labels:
      - "traefik.frontend.rule=Host:nextcloud.lavergne.online"

networks:
  proxy-network:
    external:
      name: proxy-network

volumes:
  nextcloud_data:
    external: true
  nextcloud_apps:
    external: true
  nextcloud_config:
    external: true
